apiVersion: v1
data:
  EMBEDDING_MODEL_MAX_CHUNK_LENGTH: "8192"
  EMBEDDING_MODEL_PREF: nomic-embed-text:1.5
  STORAGE_DIR: /app/server/storage
  TTS_PROVIDER: native
  VECTOR_DB: "lancedb"
  WHISPER_PROVIDER: local
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: anything-llm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: anything-llm
    app.kubernetes.io/version: 1.2.2
    helm.sh/chart: anything-llm-1.1.2
  name: anything-llm-config
  namespace: anything-llm
