apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-storage
  namespace: anything-llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3-encrypted